---

- name: change owner of wordpress
  file: 
    dest: /usr/share/wordpress
    owner: www-data
    group: root
    recurse: yes

- name: check if config file exists {{ instance.name }}
  stat:
    path: /root/.my.cnf-{{ instance.db_user }}
  register: pass_file

- name: Get wp pass
  shell: |
      cat /root/.my.cnf-{{ instance.db_user }}
  register: WORDPRESS_DB_PASSWORD
  changed_when: false
  when: pass_file.stat.exists

- name: wordpress config file
  template:
    src: etc/wordpress/config.php.j2
    dest: /etc/wordpress/config-www.{{ instance.name }}.php
    owner: root
    group: root
    mode: '0644'

