---

- name: packages role
  include_role:
    name: packages
  vars:
    PKGS_LIST: "{{ IPTABLES_PKGS_LIST }}"

- name: reload iptables
  shell: |
    iptables -I INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
    iptables -I OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
    systemctl enable iptables
    iptables-restore < /etc/iptables/rules.v4    
  changed_when: false

- name: iptables config 
  template:
    src: etc/iptables/rules.v4.j2 
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart iptables

