---

- name: packages role
  include_role:
    name: packages
  vars:
    PKGS_LIST: "{{ MARIADB_PKGS_LIST }}"

- name: check if config file exist
  stat:
    path: /root/.my.cnf
  register: config_file

- name: Generate mysql root pass
  set_fact:
    MARIADB_ROOT_PASS: "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_uppercase,ascii_lowercase,digits length=16') }}"

- name: Removes anonymous users
  community.mysql.mysql_user:
    name: ''
    host: "{{ item }}" 
    state: absent
    login_unix_socket: /run/mysqld/mysqld.sock
  with_items:
    - 127.0.0.1
    - localhost

- name: mysql .my.cnf {{ instance.name }}
  template:
    src: root/my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: '0600'
  when: not config_file.stat.exists

- name: Update MariaDB root password
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ MARIADB_ROOT_PASS }}"
  with_items:
    - 127.0.0.1
    - localhost
  when: not config_file.stat.exists

- name: configuring instances
  include_tasks: database.yml
  loop: "{{ DB_INSTANCES }}"
  loop_control:
    loop_var: instance

- name: configuring users
  include_tasks: users.yml
  loop: "{{ DB_USERS }}"
  loop_control:
    loop_var: user
