---

SHADOWSOCKS_INSTANCES:
  - name: shdsocks1
    server: 0.0.0.0
    server_port: 10081
    local_port: 1081
    timeout: 60
    method: chacha20-ietf-poly1305
    mode: tcp_and_udp
    plugin: obfs-server
    plugin_obfs: "obfs=http;obfs-host=www.google.com"
  - name: shdsocks2
    server: 0.0.0.0
    server_port: 10082
    local_port: 1082
    timeout: 60
    method: chacha20-ietf-poly1305
    mode: tcp_and_udp
    plugin: obfs-server
    plugin_obfs: "obfs=http;obfs-host=www.google.com"
  - name: shdsocks3
    server: 0.0.0.0
    server_port: 10083
    local_port: 1083
    timeout: 60
    method: chacha20-ietf-poly1305
    mode: tcp_and_udp
    plugin: obfs-server
    plugin_obfs: "obfs=http;obfs-host=www.google.com"

INPUT_CHAINS:
  - name: "INPUT_SSH"
    policy: "ACCEPT"
    rules:
      - "-s 0.0.0.0/0 -p tcp --dport 22 -j ACCEPT"
  - name: "INPUT_SHADOWSOCKS"
    policy: "ACCEPT"
    rules:
      - "-s 0.0.0.0/0 -p tcp --dport 10081 -j ACCEPT"
      - "-s 0.0.0.0/0 -p tcp --dport 10082 -j ACCEPT"
      - "-s 0.0.0.0/0 -p tcp --dport 10083 -j ACCEPT"

OUTPUT_CHAINS:
  - name: "OUTPUT_WEB"
    policy: "ACCEPT"
    rules:
      - "-d 0.0.0.0/0 -p tcp --dport 80 -j ACCEPT"
      - "-d 0.0.0.0/0 -p tcp --dport 443 -j ACCEPT"
  - name: "OUTPUT_SSH"
    policy: "ACCEPT"
    rules:
      - "-d 0.0.0.0/0 -p tcp --dport 22 -j ACCEPT"

FORWARD_CHAINS:
  - name: "FORWARD_DEFAULT"
    policy: "DROP"
    rules:
      - "-s 0.0.0.0/0 -d 0.0.0.0/0 -j DROP"

