---

INPUT_CHAINS:
  - name: "INPUT_SSH"
    policy: "ACCEPT"
    rules:
      - "-s 0.0.0.0/0 -p tcp --dport 22 -j ACCEPT"
  - name: "INPUT_WEB"
    policy: "ACCEPT"
    rules:
      - "-s 0.0.0.0/0 -p tcp --dport 80 -j ACCEPT"
      - "-s 0.0.0.0/0 -p tcp --dport 443 -j ACCEPT"

OUTPUT_CHAINS:
  - name: "OUTPUT_WEB"
    policy: "ACCEPT"
    rules:
      - "-d 0.0.0.0/0 -p tcp --dport 80 -j ACCEPT"
      - "-d 0.0.0.0/0 -p tcp --dport 443 -j ACCEPT"
  - name: "OUTPUT_SSH"
    policy: "ACCEPT"
    rules:
      - "-d 0.0.0.0/0 -p tcp --dport 22 -j ACCEPT"

FORWARD_CHAINS:
  - name: "FORWARD_DEFAULT"
    policy: "DROP"
    rules:
      - "-s 0.0.0.0/0 -d 0.0.0.0/0 -j DROP"

NGINX_INSTANCES:
  - domain: sudoer.net
    email: morteza.bashsiz@gmail.com
    root: /home/www-data/sudoer.net/www/wordpress

DB_INSTANCES:
  - name: sudoer_net

DB_USERS:
  - name: sudoer_user
    priv:
      - 'sudoer_net.*:ALL,GRANT'

WP_INSTANCES:
  - name: sudoer.net
    db: sudoer_net
    db_user: sudoer_user
    db_host: localhost 
    db_charset: utf8

