---

- hosts: shadowsocks
  
  vars_files:
    - defaults/shadowsocks.yml

  roles:
    - role: packages
      tags:
        - apt
    - role: iptables
      tags:
        - firewall
        - iptables
    - role: shadowsocks
        - shadowsocks
  
