---

- hosts: sudoer
  
  vars_files:
    - defaults/sudoer.yml

  roles:
    - role: packages
      tags:
        - apt
        - packages
    - role: iptables
      tags:
        - firewall
        - iptables
    - role: fail2ban
      tags:
        - fail2ban
    - role: sysctl
      tags:
        - sysctl
    - role: nginx
      tags:
        - nginx
